# Generated by Django 3.2.7 on 2021-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
