# Generated by Django 3.2.7 on 2021-09-08 13:29

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_discountcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(default=orders.models.random_string, max_length=100, unique=True),
        ),
    ]
